# Generated by Django 5.2.11 on 2026-02-18 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.inventory')),
            ],
        ),
    ]
