# Generated by Django 5.2.11 on 2026-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('addressid', models.AutoField(db_column='AddressID', primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Street', max_length=255, null=True)),
                ('city', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=255)),
                ('province', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Province', max_length=255, null=True)),
                ('postalcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PostalCode', max_length=20)),
                ('country', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Country', max_length=255, null=True)),
                ('addresstype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AddressType', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Customer_Address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LastName', max_length=50)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Phone', max_length=20, null=True)),
                ('registrationdate', models.DateTimeField(db_column='registrationDate')),
                ('isactive', models.BooleanField(db_column='isActive')),
            ],
            options={
                'db_table': 'Customers',
                'managed': False,
            },
        ),
    ]
