# Generated by Django 5.2.11 on 2026-02-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('logid', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('action', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Action', max_length=255)),
                ('tablename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TableName', max_length=255)),
                ('recordid', models.IntegerField(db_column='RecordID')),
                ('userid', models.IntegerField(db_column='UserID')),
                ('timestamp', models.DateTimeField(db_column='Timestamp')),
            ],
            options={
                'db_table': 'AuditLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brandid', models.AutoField(db_column='BrandID', primary_key=True, serialize=False)),
                ('brandname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BrandName', max_length=50)),
                ('branddescription', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BrandDescription', max_length=255, null=True)),
                ('logourl', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='logoURL', max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('ordercount', models.IntegerField(db_column='OrderCount')),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CategoryName', max_length=50)),
            ],
            options={
                'db_table': 'Categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('orderdetailid', models.AutoField(db_column='OrderDetailID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('unitprice', models.DecimalField(db_column='UnitPrice', decimal_places=2, max_digits=10)),
                ('totalprice', models.DecimalField(blank=True, db_column='TotalPrice', decimal_places=2, max_digits=21, null=True)),
            ],
            options={
                'db_table': 'OrderDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('ordernumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='OrderNumber', max_length=50, unique=True)),
                ('orderdate', models.DateTimeField(db_column='OrderDate')),
                ('totalamount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('estimateddeliverydate', models.DateTimeField(blank=True, db_column='EstimatedDeliveryDate', null=True)),
                ('trackingnumber', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrackingNumber', max_length=50, null=True)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
                ('updatedat', models.DateTimeField(db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderstatus',
            fields=[
                ('orderstatusid', models.AutoField(db_column='OrderStatusID', primary_key=True, serialize=False)),
                ('statusname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='StatusName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'OrderStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymentmethods',
            fields=[
                ('methodid', models.AutoField(db_column='MethodID', primary_key=True, serialize=False)),
                ('methodname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MethodName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'PaymentMethods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('discountpercent', models.DecimalField(blank=True, db_column='DiscountPercent', decimal_places=2, max_digits=5, null=True)),
                ('payableamount', models.DecimalField(blank=True, db_column='PayableAmount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('sku', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SKU', max_length=50, unique=True)),
                ('productname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProductName', max_length=100)),
                ('sellingprice', models.DecimalField(db_column='SellingPrice', decimal_places=2, max_digits=10)),
                ('costprice', models.DecimalField(db_column='CostPrice', decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('reorderlevel', models.IntegerField(blank=True, db_column='ReorderLevel', null=True)),
                ('productdescription', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProductDescription', max_length=255, null=True)),
                ('productimageurl', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProductImageURL', max_length=255, null=True)),
                ('productspecifications', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProductSpecifications', max_length=3000, null=True)),
                ('unitssold', models.IntegerField(db_column='UnitsSold')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchaseorderdetails',
            fields=[
                ('purchaseorderdetailid', models.AutoField(db_column='PurchaseOrderDetailID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('unitcost', models.DecimalField(db_column='UnitCost', decimal_places=2, max_digits=10)),
                ('totalcost', models.DecimalField(blank=True, db_column='TotalCost', decimal_places=2, max_digits=21, null=True)),
            ],
            options={
                'db_table': 'PurchaseOrderDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchaseorders',
            fields=[
                ('purchaseorderid', models.AutoField(db_column='PurchaseOrderID', primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(db_column='OrderDate')),
                ('totalamount', models.DecimalField(blank=True, db_column='TotalAmount', decimal_places=2, max_digits=10, null=True)),
                ('expecteddeliverydate', models.DateTimeField(blank=True, db_column='ExpectedDeliveryDate', null=True)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'PurchaseOrders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewid', models.AutoField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=1, null=True)),
                ('comment', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comment', max_length=255, null=True)),
                ('reviewdate', models.DateTimeField(db_column='ReviewDate')),
            ],
            options={
                'db_table': 'Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplierid', models.AutoField(db_column='SupplierID', primary_key=True, serialize=False)),
                ('suppliername', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SupplierName', max_length=100)),
                ('contactpersonname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContactPersonName', max_length=50, null=True)),
                ('contactemail', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContactEmail', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Phone', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Country', max_length=255, null=True)),
                ('isactive', models.BooleanField(db_column='isActive')),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewActiveCustomers',
            fields=[
                ('customerid', models.IntegerField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
            ],
            options={
                'db_table': 'vw_ActiveCustomers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewLowStockProducts',
            fields=[
                ('productid', models.IntegerField(db_column='ProductID', primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='ProductName', max_length=100)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('reorderlevel', models.IntegerField(db_column='ReorderLevel')),
            ],
            options={
                'db_table': 'vw_LowStockProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewOrderSummary',
            fields=[
                ('orderid', models.IntegerField(db_column='OrderID', primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='CustomerName', max_length=100)),
                ('statusname', models.CharField(db_column='StatusName', max_length=50)),
                ('orderdate', models.DateTimeField(db_column='OrderDate')),
                ('totalamount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'vw_OrderSummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewProductInventory',
            fields=[
                ('productid', models.IntegerField(db_column='ProductID', primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='ProductName', max_length=100)),
                ('categoryname', models.CharField(db_column='CategoryName', max_length=50)),
                ('brandname', models.CharField(db_column='BrandName', max_length=50)),
                ('suppliername', models.CharField(db_column='SupplierName', max_length=50)),
                ('sellingprice', models.DecimalField(db_column='SellingPrice', decimal_places=2, max_digits=10)),
                ('costprice', models.DecimalField(db_column='CostPrice', decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('reorderlevel', models.IntegerField(db_column='ReorderLevel')),
            ],
            options={
                'db_table': 'vw_ProductInventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Whishlist',
            fields=[
                ('wishlistid', models.AutoField(db_column='WishlistID', primary_key=True, serialize=False)),
                ('addedat', models.DateTimeField(db_column='AddedAt')),
            ],
            options={
                'db_table': 'Whishlist',
                'managed': False,
            },
        ),
    ]
