# Generated by Django 5.2.11 on 2026-02-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_brands_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderdetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='purchaseorders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='viewactivecustomers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='viewlowstockproducts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='viewordersummary',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='viewproductinventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='whishlist',
            options={'managed': False},
        ),
    ]
